# **CODE SENTINEL Internship**

## **Task 1:**
Download a dataset (e.g., Iris, Titanic, or your own .csv).
Write a script that:
Loads the dataset with pandas
Displays column names, number of rows, data types
Shows summary statistics (.describe())
Checks for missing values

ðŸ›  Tools: pandas

ðŸŽ¯ Goal: Understand data structure, detect missing or
inconsistent data.

Step 1: importing Library

In [1]:
import pandas as pd

Step 2: Loading dataset with pandas

In [2]:
file_path = "/content/Car_sales.csv"
df = pd.read_csv(file_path)

Step 3: Displaying few rows

In [3]:
df.head()

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639

Step 4:
*   Display column names
*   Display number of rows and colmns
*   Display data types

In [7]:
# Display column names
print(" Column Names:")
print(df.columns.tolist())

 Column Names:
['Manufacturer', 'Model', 'Sales_in_thousands', '__year_resale_value', 'Vehicle_type', 'Price_in_thousands', 'Engine_size', 'Horsepower', 'Wheelbase', 'Width', 'Length', 'Curb_weight', 'Fuel_capacity', 'Fuel_efficiency', 'Latest_Launch', 'Power_perf_factor']

In [8]:
# Display number of rows and columns
print("\n Shape of dataset (rows, columns):")
print(df.shape)

 Shape of dataset (rows, columns):
(157, 16)

In [9]:
# Display data types
print("\n Data Types:")
print(df.dtypes)

 Data Types:
Manufacturer            object
Model                   object
Sales_in_thousands     float64
__year_resale_value    float64
Vehicle_type            object
Price_in_thousands     float64
Engine_size            float64
Horsepower             float64
Wheelbase              float64
Width                  float64
Length                 float64
Curb_weight            float64
Fuel_capacity          float64
Fuel_efficiency        float64
Latest_Launch           object
Power_perf_factor      float64
dtype: object

Step 5: Summary Statistics

In [10]:
print("Summary Statistics:")
df.describe(include="all")

Summary Statistics:

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
count,157,157,157.000000,121.000000,157,155.000000,156.000000,156.000000,156.000000,156.000000,156.000000,155.000000,156.000000,154.000000,157,155.000000
unique,30,156,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,130,NaN
top,Ford,Neon,NaN,NaN,Passenger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1/29/2012,NaN
freq,11,2,NaN,NaN,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN
mean,NaN,NaN,52.998076,18.072975,NaN,27.390755,3.060897,185.948718,107.487179,71.150000,187.343590,3.378026,17.951923,23.844156,NaN,77.043591
std,NaN,NaN,68.029422,11.453384,NaN,14.351653,1.044653,56.700321,7.641303,3.451872,13.431754,0.630502,3.887921,4.282706,NaN,25.142664
min,NaN,NaN,0.110000,5.160000,NaN,9.235000,1.000000,55.000000,92.600000,62.600000,149.400000,1.895000,10.300000,15.000000,NaN,23.276272
25%,NaN,NaN,14.114000,11.260000,NaN,18.017500,2.300000,149.500000,103.000000,68.400000,177.575000,2.971000,15.800000,21.000000,NaN,60.407707
50%,NaN,NaN,29.450000,14.180000,NaN,22.799000,3.000000,177.500000,107.000000,70.550000,187.900000,3.342000,17.200000,24.000000,NaN,72.030917
75%,NaN,NaN,67.956000,19.875000,NaN,31.947500,3.575000,215.000000,112.200000,73.425000,196.125000,3.799500,19.575000,26.000000,NaN,89.414878
max,NaN,NaN,540.561000,67.550000,NaN,85.500000,8.000000,450.000000,138.700000,79.900000,224.500000,5.572000,32.000000,45.000000,NaN,188.144323

Step 6: Missing Values Check

In [11]:
print(df.isnull())

     Manufacturer  Model  Sales_in_thousands  __year_resale_value  \
0           False  False               False                False
1           False  False               False                False
2           False  False               False                False
3           False  False               False                False
4           False  False               False                False
..            ...    ...                 ...                  ...
152         False  False               False                 True
153         False  False               False                 True
154         False  False               False                 True
155         False  False               False                 True
156         False  False               False                 True

     Vehicle_type  Price_in_thousands  Engine_size  Horsepower  Wheelbase  \
0           False               False        False       False      False
1           False               False        False       False      False
2           False                True        False       False      False
3           False               False        False       False      False
4           False               False        False       False      False
..            ...                 ...          ...         ...        ...
152         False               False        False       False      False
153         False               False        False       False      False
154         False               False        False       False      False
155         False               False        False       False      False
156         False               False        False       False      False

     Width  Length  Curb_weight  Fuel_capacity  Fuel_efficiency  \
0    False   False        False          False            False
1    False   False        False          False            False
2    False   False        False          False            False
3    False   False        False          False            False
4    False   False        False          False            False
..     ...     ...          ...            ...              ...
152  False   False        False          False            False
153  False   False        False          False            False
154  False   False        False          False            False
155  False   False        False          False            False
156  False   False        False          False            False

     Latest_Launch  Power_perf_factor
0            False              False
1            False              False
2            False               True
3            False              False
4            False              False
..             ...                ...
152          False              False
153          False              False
154          False              False
155          False              False
156          False              False

[157 rows x 16 columns]

**Missing values per column**

In [12]:
print("Missing Values per Column:")
print(df.isnull().sum())

Missing Values per Column:
Manufacturer            0
Model                   0
Sales_in_thousands      0
__year_resale_value    36
Vehicle_type            0
Price_in_thousands      2
Engine_size             1
Horsepower              1
Wheelbase               1
Width                   1
Length                  1
Curb_weight             2
Fuel_capacity           1
Fuel_efficiency         3
Latest_Launch           0
Power_perf_factor       2
dtype: int64